export const ADD_STUDENT_BIODATA = 'ADD_STUDENT_BIODATA';
export const ADD_STUDENT_NOKDATA = 'ADD_STUDENT_NOKDATA';
export const ADD_STUDENT_GUARDDATA = 'ADD_STUDENT_GUARDDATA';
export const ADD_STUDENT_RECORD_DATA = 'ADD_STUDENT_RECORD_DATA';
export const ADD_STUDENT_PREVIOUS_DATA = 'ADD_STUDENT_PREVIOUS_DATA';
export const ADD_STUDENT_NEEDS_DATA = 'ADD_STUDENT_NEEDS_DATA';
export const ADD_STUDENT_VULNERABILITY_DATA = 'ADD_STUDENT_VULNERABILITY_DATA';
export const ADD_STUDENT_OTHER_DATA = 'ADD_STUDENT_OTHER_DATA';
export const SAVE_STUDENT_DATA = 'SAVE_STUDENT_DATA';

export const ADD_TEACHER_BIODATA = 'ADD_TEACHER_BIODATA';
export const ADD_TEACHER_NOKDATA = 'ADD_TEACHER_NOKDATA';
export const ADD_TEACHER_RECORD_DATA = 'ADD_TEACHER_RECORD_DATA';
export const ADD_TEACHER_QUALIFICATION_DATA = 'ADD_TEACHER_QUALIFICATION_DATA';
export const ADD_TEACHER_SUBJECT_DATA = 'ADD_TEACHER_SUBJECT_DATA';
export const ADD_TEACHER_STREAM_DATA = 'ADD_TEACHER_STREAM_DATA';
export const ADD_TEACHER_SPECIALISATION_DATA = 'ADD_TEACHER_SPECIALISATION_DATA';
export const ADD_TEACHER_INSTITUTION_DATA = 'ADD_TEACHER_INSTITUTION_DATA';
export const ADD_TEACHER_POSTING_DATA = 'ADD_TEACHER_POSTING_DATA';
export const SAVE_TEACHER_DATA = 'SAVE_TEACHER_DATA';

export const ADD_SCHOOL_DATA = 'ADD_SCHOOL_DATA';
export const ADD_SCHOOL_RECORD_DATA = 'ADD_SCHOOL_RECORD_DATA';
export const ADD_SCHOOL_CORDINATES = 'ADD_SCHOOL_CORDINATES';
export const ADD_SCHOOL_EDUCATIONAL_LEVELS = 'ADD_SCHOOL_EDUCATIONAL_LEVELS';
export const ADD_SCHOOL_GRANT = 'ADD_SCHOOL_GRANT';
export const ADD_SCHOOL_ENROLLMENT_CERTIFICATES = 'ADD_SCHOOL_ENROLLMENT_CERTIFICATES';
export const ADD_SCHOOL_FACILITIES = 'ADD_SCHOOL_FACILITIES';
export const ADD_SCHOOL_POWER_SOURCES = 'ADD_SCHOOL_POWER_SOURCES';
export const ADD_SCHOOL_HEALTH_FACILITIES = 'ADD_SCHOOL_HEALTH_FACILITIES';
export const ADD_SCHOOL_CLASSES = 'ADD_SCHOOL_CLASSES';
export const ADD_SCHOOL_STREAMS = 'ADD_SCHOOL_STREAMS';
export const SAVE_SCHOOL_DATA = 'SAVE_SCHOOL_DATA';


export const LOAD_STUDENT_DATA = 'LOAD_STUDENT_DATA';
export const LOAD_TEACHER_DATA = 'LOAD_TEACHER_DATA';
export const LOAD_SCHOOL_DATA = 'LOAD_SCHOOL_DATA';

export const FETCH_ERROR = 'FETCH_ERROR';
export const FETCH_LOADING = 'FETCH_LOADING';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_STATES = 'FETCH_STATES';
export const FETCH_LGAS = 'FETCH_LGAS';
export const FETCH_LGAS_BY_STATE = 'FETCH_LGAS_BY_STATE';
export const FETCH_GENDERS = 'FETCH_GENDERS';

export const FETCH_RELATIONSHIPS = 'FETCH_RELATIONSHIPS';
export const FETCH_SCHOOLS = 'FETCH_SCHOOLS';
export const FETCH_STUDENT_CLASSES = 'FETCH_STUDENT_CLASSES';
export const FETCH_STUDENT_STREAMS = 'FETCH_STUDENT_STREAMS';
export const FETCH_SPECIAL_NEEDS = 'FETCH_SPECIAL_NEEDS';
export const FETCH_VULNERABILITIES = 'FETCH_VULNERABILITIES';

export const FETCH_SUBJECTS = 'FETCH_SUBJECTS';
export const FETCH_STAFF_CLASSES = 'FETCH_STAFF_CLASSES';
export const FETCH_STAFF_TYPES = 'FETCH_STAFF_TYPES';
export const FETCH_RANK = 'FETCH_RANK';
export const FETCH_QUALIFICATION = 'FETCH_QUALIFICATION';
export const FETCH_SUBJECT_AREA = 'FETCH_SUBJECT_AREA';
export const FETCH_GRADE_LEVEL = 'FETCH_GRADE_LEVEL';
export const FECTH_GRADE_LEVEL ='FECTH_GRADE_LEVEL';

export const FETCH_EDUCATION_LEVELS = 'FETCH_EDUCATION_LEVELS';
export const FETCH_LOCATIONS = 'FETCH_LOCATIONS';
export const FETCH_SCHOOL_TYPES = 'FETCH_SCHOOL_TYPES';
export const FETCH_SCHOOL_MIXS = 'FETCH_SCHOOL_MIXS';
export const FETCH_SECURITIES = 'FETCH_SECURITIES';
export const FETCH_PARENT_FORUMS = 'FETCH_PARENT_FORUMS';
export const FETCH_INSPECTION_AUTHORITY = 'FETCH_INSPECTION_AUTHORITY';
export const FETCH_GRANTS = 'FETCH_GRANTS';
export const FETCH_OWNERSHIP = 'FETCH_OWNERSHIP';
export const FETCH_FACILITIES = 'FETCH_FACILITIES';
export const FETCH_POWER_SOURCES = 'FETCH_POWER_SOURCES';
export const FETCH_HEALTH_FACILITIES = 'FETCH_HEALTH_FACILITIES';
export const RESET_DATA = "RESET_DATA"